---
title: "Biblical Word Usage to Forgive"
author: "Parker Oakes"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(networkD3)
library(dplyr)
setwd("C:/Users/oakespar/Documents/forgive")
links <- read.csv(file = "forgive_sankey.csv", 
         header = TRUE,
         sep = ',',
         encoding = 'UTF-8')
```


# Program A Sankey Diagram with CSV
```{r}

colnames(links) <- c('source', 'target', 'value')

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame(
  name=c(as.character(links$source), as.character(links$target)) %>% 
    unique()
)

# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
links$IDsource <- match(links$source, nodes$name)-1 
links$IDtarget <- match(links$target, nodes$name)-1

# Make the Network. I call my colour scale with the colourScale argument
sankeyNetwork(Links = links, 
              Nodes = nodes, 
              Source = "IDsource", 
              Target = "IDtarget", 
              Value = "value", 
              NodeID = "name",
              fontSize = 14)

```
